version: '3.8'

services:
  app:
    depends_on:
      - dynamodb-local
    build:
      context: .
      dockerfile: Dockerfile-local
    container_name: empowerment-app
    entrypoint: [ "yarn", "start:dev" ]
    restart: always
    ports:
      - "${PORT}:${PORT}"
    environment:
      PORT: ${PORT}

  dynamodb_admin:
    image: aaronshaf/dynamodb-admin
    container_name: app-dynamodb_admin
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb-local:8000
    depends_on:
      - dynamodb-local
    restart: unless-stopped

  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    restart: unless-stopped
    ports:
      - "8000:8000"
    user: root
    volumes:
      - ../tmp/dynamodb:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"

